slicer:
  ros__parameters:
    joints: ['catheter_lin', 'catheter_rot', 'catheter_bend', 
      'sheath_lin', 'sheath_rot', 'sheath_bend']
    keys: ['i', 'k', 'l', 'j', 'o', 'u', 
      'w', 's', 'd', 'a', 'e', 'q']
    key_joint_idx: [0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5]
    directions: [1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1]
    joint_vels: [5.0, 30.0, 30.0, 5.0, 30.0, 1.0]

igtl_node:
  ros__parameters:
    RIB_server_ip: "0.0.0.0"
    RIB_port: 18944
    RIB_type: "server"